**DAV-LAB\
NAME-VAISHNAV BALPANDE\
SECTION-5B\
ROLL NO-01\
LAB1-ASSIGNMENT**

In [1]:
import pandas as pd

df = pd.read_csv('data.csv')

In [2]:
df.head()

   student_id       student_name student_branch student_section
0           1  VAISHNAV BALPANDE           AIML              C1
1           2       ISHA BHANGRE            CSE              A1
2           3    TANUSHRI SAPATE           AIDS              B1
3           4      ISHIKA SAHARE          CYBER              D1
4           5       SOHAM ADMANE           AIML              C2

In [3]:
df.tail()

    student_id     student_name student_branch student_section
12          13  SHRADDHA SHARMA           AIML              C1
13          14  SHREYANK NIPANE            CSE              A1
14          15      KASAK PATEL           AIDS              B1
15          16        ARYA MORE          CYBER              D1
16          17              NaN           AIML              C2

In [4]:
df.describe()

       student_id
count   17.000000
mean     9.000000
std      5.049752
min      1.000000
25%      5.000000
50%      9.000000
75%     13.000000
max     17.000000

In [5]:
df.isnull().sum()

student_id         0
student_name       1
student_branch     0
student_section    0
dtype: int64

In [6]:
df.shape

(17, 4)

In [7]:
df.columns

Index(['student_id', 'student_name', 'student_branch', 'student_section'], dtype='str')

In [8]:
df.info

<bound method DataFrame.info of     student_id       student_name student_branch student_section
0            1  VAISHNAV BALPANDE           AIML              C1
1            2       ISHA BHANGRE            CSE              A1
2            3    TANUSHRI SAPATE           AIDS              B1
3            4      ISHIKA SAHARE          CYBER              D1
4            5       SOHAM ADMANE           AIML              C2
5            6  MADHAVI KATEKHAYE            CSE              A2
6            7     HANSHAL BOBATE           AIDS              B2
7            8    AASTHA PUSDEKAR          CYBER              D1
8            9  DHANASHREE SAINIS           AIML              C3
9           10      RIYA WAGHMARE            CSE              A3
10          11      LOKESH PARATE           AIDS              B3
11          12      VIBHA SATPUTE          CYBER              D1
12          13    SHRADDHA SHARMA           AIML              C1
13          14    SHREYANK NIPANE            CSE              A1
14          15        KASAK PATEL           AIDS              B1
15          16          ARYA MORE          CYBER              D1
16          17                NaN           AIML              C2>

**Operations on Text File**

In [9]:
import pandas as pd
df2 = pd.read_csv('random_data.txt')

In [10]:
df2.head()

,id,category,value
0,1,A,10.5
1,2,B,20.1
2,3,A,15.3
3,This is the first paragraph. It contains some ...,20,and 30.
4,The text characters are varied! We have letters,digits,and punctuation.

In [11]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        116 non-null    str
 1   category  12 non-null     str
 2   value     10 non-null     str
dtypes: str(3)
memory usage: 2.8 KB

In [12]:
df2.describe()

            id category value
count      116       12    10
unique     110        5    10
top     python        A  10.5
freq         3        4     1

In [13]:
df2.isnull().sum()

id            0
category    104
value       106
dtype: int64

In [14]:
df2.dropna(inplace=True)
df2.shape

(10, 3)

**Operations on JSON File**

In [15]:
import json
import pandas as pd

with open('inventory.json', 'r') as f:
    data_json = json.load(f)

df_json = pd.DataFrame(data_json)
df_json.head()

    id                item    price  stock         category
0  101       Sofa Model 36   772.85    675        Furniture
1  102  Bookshelf Model 89   522.80    718        Furniture
2  103    Folders Model 11   414.55     92  Office Supplies
3  104      Chair Model 64  1766.03    919        Furniture
4  105    T-Shirt Model 60   331.36    244         Clothing

In [16]:
len(df_json)

2056

In [17]:
df_json.groupby('category')['stock'].sum()

category
Clothing           193291
Electronics        202488
Furniture          224370
Groceries          179499
Office Supplies    208347
Name: stock, dtype: int64

**Operations on XML File**

In [18]:
import xml.etree.ElementTree as ET

tree = ET.parse('inventory.xml')
root = tree.getroot()

xml_data = []
for item in root.findall('item'):
    entry = {}
    for child in item:
        entry[child.tag] = child.text
    xml_data.append(entry)

xml_data[:5]

[{'id': '101',
  'name': 'Laptop',
  'price': '1200.50',
  'stock': '45',
  'category': 'Electronics'},
 {'id': '102',
  'name': 'Mouse',
  'price': '25.00',
  'stock': '200',
  'category': 'Electronics'},
 {'id': '103',
  'name': 'Desk',
  'price': '150.00',
  'stock': '15',
  'category': 'Furniture'},
 {'id': '104',
  'name': 'Chair',
  'price': '85.50',
  'stock': '30',
  'category': 'Furniture'},
 {'id': '105',
  'name': 'Monitor',
  'price': '300.00',
  'stock': '80',
  'category': 'Electronics'}]

In [19]:
len(xml_data)

5

In [20]:
stock_per_category_xml = {}
for entry in xml_data:
    cat = entry['category']
    stock = int(entry['stock'])
    stock_per_category_xml[cat] = stock_per_category_xml.get(cat, 0) + stock

stock_per_category_xml

{'Electronics': 325, 'Furniture': 45}